src/Entity/Ligue.php
<?php

namespace App\Entity;

use App\Repository\LigueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LigueRepository::class)
 */
class Ligue
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\OneToMany(targetEntity=LigueMembre::class, mappedBy="id_ligue")
     */
    private $ligueMembres;

    public function __construct()
    {
        $this->ligueMembres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection<int, LigueMembre>
     */
    public function getLigueMembres(): Collection
    {
        return $this->ligueMembres;
    }

    public function addLigueMembre(LigueMembre $ligueMembre): self
    {
        if (!$this->ligueMembres->contains($ligueMembre)) {
            $this->ligueMembres[] = $ligueMembre;
            $ligueMembre->setIdLigue($this);
        }

        return $this;
    }

    public function removeLigueMembre(LigueMembre $ligueMembre): self
    {
        if ($this->ligueMembres->removeElement($ligueMembre)) {
            // set the owning side to null (unless already changed)
            if ($ligueMembre->getIdLigue() === $this) {
                $ligueMembre->setIdLigue(null);
            }
        }

        return $this;
    }
}

src/Form/LigueType.php
<?php

namespace App\Form;

use App\Entity\Ligue;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LigueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('date_creation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ligue::class,
        ]);
    }
}

src/Controller/LigueController.php
<?php

namespace App\Controller;

use App\Entity\Ligue;
use App\Form\LigueType;
use App\Repository\LigueRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/ligue')]
class LigueController extends AbstractController
{
    #[Route('/', name: 'ligue_index', methods: ['GET'])]
    public function index(LigueRepository $ligueRepository): Response
    {
        return $this->render('ligue/index.html.twig', [
            'ligues' => $ligueRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'ligue_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $ligue = new Ligue();
        $form = $this->createForm(LigueType::class, $ligue);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($ligue);
            $entityManager->flush();

            return $this->redirectToRoute('ligue_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ligue/new.html.twig', [
            'ligue' => $ligue,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'ligue_show', methods: ['GET'])]
    public function show(Ligue $ligue): Response
    {
        return $this->render('ligue/show.html.twig', [
            'ligue' => $ligue,
        ]);
    }

    #[Route('/{id}/edit', name: 'ligue_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Ligue $ligue, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LigueType::class, $ligue);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('ligue_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ligue/edit.html.twig', [
            'ligue' => $ligue,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'ligue_delete', methods: ['POST'])]
    public function delete(Request $request, Ligue $ligue, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ligue->getId(), $request->request->get('_token'))) {
            $entityManager->remove($ligue);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ligue_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ligue/_delete_form.html.twig
<form method="post" action="{{ path('ligue_delete', {'id': ligue.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ligue.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ligue/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/ligue/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ligue{% endblock %}

{% block body %}
    <h1>Edit Ligue</h1>

    {{ include('ligue/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('ligue_index') }}">back to list</a>

    {{ include('ligue/_delete_form.html.twig') }}
{% endblock %}

templates/ligue/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ligue index{% endblock %}

{% block body %}
    <img src="https://upload.wikimedia.org/wikipedia/fr/thumb/f/fe/Logo_Betclic_2019.svg/1200px-Logo_Betclic_2019.svg.png">
    <h1>Notre site de paris pour les nuls</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Date_creation</th>
            </tr>
        </thead>
        <tbody>
        {% for ligue in ligues %}
            <tr>
                <td>{{ ligue.id }}</td>
                <td>{{ ligue.nom }}</td>
                <td>{{ ligue.dateCreation ? ligue.dateCreation|date('Y-m-d H:i:s') : '' }}</td>

            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('ligue_new') }}">Create new</a>
{% endblock %}

templates/ligue/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ligue{% endblock %}

{% block body %}
    <h1>Create new Ligue</h1>

    {{ include('ligue/_form.html.twig') }}

    <a href="{{ path('ligue_index') }}">back to list</a>
{% endblock %}

templates/ligue/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ligue{% endblock %}

{% block body %}
    <h1>Ligue</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ ligue.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ ligue.nom }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ ligue.dateCreation ? ligue.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('ligue_index') }}">back to list</a>

    <a href="{{ path('ligue_edit', {'id': ligue.id}) }}">edit</a>

    {{ include('ligue/_delete_form.html.twig') }}
{% endblock %}